INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (492, 123, 4, 2026, 9, 364.45000000000005, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (493, 124, 1, 2026, 9, 386.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (494, 124, 2, 2026, 9, 290.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (495, 124, 3, 2026, 9, 290.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (496, 124, 4, 2026, 9, 968.4000000000001, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (497, 125, 1, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (498, 125, 2, 2026, 9, 40.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (499, 125, 3, 2026, 9, 40.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (500, 125, 4, 2026, 9, 120.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (501, 126, 1, 2026, 9, 65.0, 65.0, '2026-09-04', NULL, 1);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (502, 126, 2, 2026, 9, 50.0, 50.0, '2026-09-04', NULL, 1);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (503, 126, 3, 2026, 9, 50.0, 50.0, '2026-09-04', NULL, 1);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (504, 126, 4, 2026, 9, 159.2, 159.2, '2026-09-04', NULL, 1);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (505, 127, 1, 2026, 9, 75.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (506, 127, 2, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (507, 127, 3, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (508, 127, 4, 2026, 9, 184.5, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (509, 128, 1, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (510, 128, 2, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (511, 128, 3, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (512, 128, 4, 2026, 9, 165.25, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (513, 129, 1, 2026, 9, 0.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (514, 129, 2, 2026, 9, 0.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (515, 129, 3, 2026, 9, 0.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (516, 129, 4, 2026, 9, 0.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (517, 130, 1, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (518, 130, 2, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (519, 130, 3, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (520, 130, 4, 2026, 9, 205.25, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (521, 131, 1, 2026, 9, 65.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (522, 131, 2, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (523, 131, 3, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (524, 131, 4, 2026, 9, 159.2, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (525, 132, 1, 2026, 9, 100.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (526, 132, 2, 2026, 9, 130.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (527, 132, 3, 2026, 9, 100.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (528, 132, 4, 2026, 9, 318.4, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (529, 133, 1, 2026, 9, 35.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (530, 133, 2, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (531, 133, 3, 2026, 9, 35.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (532, 133, 4, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (533, 134, 1, 2026, 9, 80.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (534, 134, 2, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (535, 134, 3, 2026, 9, 60.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (536, 134, 4, 2026, 9, 205.25, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (537, 135, 1, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (538, 135, 2, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (539, 135, 3, 2026, 9, 50.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (540, 135, 4, 2026, 9, 110.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (541, 136, 1, 2026, 9, 90.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (542, 136, 2, 2026, 9, 90.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (543, 136, 3, 2026, 9, 90.0, 0.0, NULL, NULL, 0);
INSERT INTO recebimentos_mensais (id, cliente_id, socio_id, ano, mes, valor_esperado, valor_recebido, data_recebimento, observacao, recebido) VALUES (544, 136, 4, 2026, 9, 90.0, 0.0, NULL, NULL, 0);
SELECT setval('recebimentos_mensais_id_seq', (SELECT MAX(id) FROM recebimentos_mensais));
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (1, 1, 2026, 9, 1200.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (2, 2, 2026, 9, 1500.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (3, 3, 2026, 9, 70.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (4, 4, 2026, 9, 2500.0, 2500.0, '2026-09-04', NULL, 1);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (5, 5, 2026, 9, 500.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (6, 6, 2026, 9, 300.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (7, 7, 2026, 9, 2500.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (8, 8, 2026, 9, 500.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (9, 9, 2026, 9, 300.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (10, 10, 2026, 9, 1000.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (11, 11, 2026, 9, 650.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (12, 12, 2026, 9, 650.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (13, 13, 2026, 9, 350.0, 0.0, NULL, NULL, 0);
INSERT INTO pagamentos_mensais (id, despesa_id, ano, mes, valor_esperado, valor_pago, data_pagamento, observacao, pago) VALUES (14, 14, 2026, 9, 500.0, 0.0, NULL, NULL, 0);
SELECT setval('pagamentos_mensais_id_seq', (SELECT MAX(id) FROM pagamentos_mensais));
SELECT setval('receitas_extras_id_seq', (SELECT MAX(id) FROM receitas_extras));